### ISSUE TITLE
03-advanced-react Tutorial import links are all broken

### ISSUE THREAD

**Issue by longtimedeveloper** [john-smilga/react-course-v3#11]
broken in tutorial `import Final from './tutorial/1-useState/final/1-error-example';`

actual: `import Final from './tutorial/01-useState/final/01-error-example';`

import statements in tutorial required updating to match new folder structure.

**Comment by john-smilga** [comment]
Thank you. So during video I use 1- and now the files start with 0?

**Comment by longtimedeveloper** [comment]
> Thank you. So during video I use 1- and now the files start with 0?

yes, that is the problem.

**Comment by john-smilga** [comment]
Oh, I see. I think I'm just going to leave it as it is.
