### ISSUE TITLE
Mixmaster Project SearchForm Component

### ISSUE THREAD

**Issue by liamli99** [john-smilga/react-course-v3#23]
[Code](https://github.com/john-smilga/react-course-v3/blob/main/09-mixmaster/final/src/components/SearchForm.jsx) line 6 seems to be useless because based on the [Documentation](https://reactrouter.com/en/main/hooks/use-navigation#navigationstate), the `navigation.state` is 'submitting' only when the form submission uses POST, PUT, PATCH, or DELETE, but here it is GET.

**Comment by john-smilga** [comment]
Please raise the issue in course Q&A
